namespace AIKnowledgeAssistant.Domain.Entities;

/// <summary>
/// Represents a single question-answer exchange in the chat system.
/// 
/// DOMAIN RESPONSIBILITY:
/// - Store chat history
/// - Track which user asked what
/// - Preserve the AI's answer for audit/logging
/// 
/// USER JOURNEY:
/// 1. User logs in
/// 2. User uploads "HR_Policy.pdf"
/// 3. User types: "How many vacation days?"
/// 4. System creates Conversation: Question, Answer, timestamp
/// 5. System links relevant DocumentChunks as sources
/// 6. User can see chat history later
/// 
/// WHY STORE CONVERSATIONS?
/// - Audit trail (compliance requirements)
/// - User can review past Q&A exchanges
/// - Identify common questions (product insights)
/// - Debug AI responses
/// - Improve embeddings/chunks based on questions
/// 
/// RELATIONSHIP:
/// User (1) ---- (Many) Conversations
///         └── Each user has many Q&A exchanges
/// 
/// Conversation (1) ---- (Many) MessageSources
///           └── Each Q&A has multiple sources cited
/// </summary>
public class Conversation
{
    /// <summary>
    /// Unique identifier for this conversation/Q&A exchange.
    /// GUID prevents ID guessing attacks.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The user who asked this question.
    /// Foreign key to User table.
    /// 
    /// BUSINESS RULE:
    /// - Every conversation must belong to exactly one user
    /// - Users cannot see other users' conversations
    /// - Conversations are private/personal
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Navigation property to the User.
    /// Set by Entity Framework.
    /// </summary>
    public User? User { get; set; }

    /// <summary>
    /// The question asked by the user.
    /// 
    /// EXAMPLE:
    /// "How many vacation days do employees get?"
    /// "When does the fiscal year end?"
    /// "What are the remote work policies?"
    /// 
    /// WHY STORE THIS?
    /// - Show in chat history
    /// - Analyze common questions
    /// - Debug why AI gave certain answer
    /// - Search through past questions
    /// 
    /// TECHNICAL NOTE:
    /// - This is the raw user question (before embedding)
    /// - For search: generate embedding from this
    /// - For storage: keep original for audit trail
    /// </summary>
    public string Question { get; set; } = string.Empty;

    /// <summary>
    /// The answer generated by the AI model.
    /// 
    /// EXAMPLE:
    /// "Employees receive 25 vacation days per year, 
    ///  plus 10 sick days and 5 personal days."
    /// 
    /// WHY STORE THIS?
    /// - Chat history: Show user what AI said
    /// - Audit trail: Verify AI accuracy
    /// - Compliance: Some industries require Q&A logs
    /// - Analytics: Track AI performance over time
    /// - Debugging: If answer was wrong, see what was generated
    /// 
    /// STORAGE CONSIDERATION:
    /// - Could be up to several paragraphs
    /// - TEXT field in database (allows long strings)
    /// - Not indexed for performance (retrieval by ID is primary query)
    /// 
    /// PRIVACY NOTE:
    /// If using external LLM API (OpenAI/Azure):
    /// - Check data residency requirements
    /// - Some customers need data to stay in specific region
    /// - Have option to NOT store answer (compliance mode)
    /// </summary>
    public string Answer { get; set; } = string.Empty;

    /// <summary>
    /// When this conversation occurred.
    /// 
    /// AUDIT PURPOSES:
    /// - Know exactly when user asked question
    /// - Identify trends: "Most questions asked on Mondays"
    /// - Compliance: Show question-answer timeline
    /// - Debugging: Correlate with system errors/logs
    /// 
    /// TIMEZONE NOTE:
    /// Always use UTC (DateTime.UtcNow)
    /// - Database stores UTC
    /// - Application converts to user's timezone for display
    /// - Prevents timezone confusion in logs
    /// 
    /// EXAMPLE: User in Belgium asks question at 10 AM local time
    /// - Stored in DB: 08:00 UTC (2 hours behind)
    /// - Displayed in UI: 10:00 CET (user's timezone)
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Optional: When this conversation was last updated.
    /// 
    /// USE CASES FOR UPDATES:
    /// - User feedback: "This answer was wrong"
    /// - AI regeneration: "Please give me a better answer"
    /// - Manual correction: Admin fixes AI answer
    /// - Rating: User rates answer quality (1-5 stars)
    /// 
    /// For v1: Keep simple, just track creation time
    /// For v2: Add UpdatedAt for corrections
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Collection of source citations for this answer.
    /// 
    /// RELATIONSHIP:
    /// Conversation (1) ---- (Many) MessageSources
    ///
    /// EXAMPLE:
    /// Question: "How many vacation days?"
    /// Answer: "25 days per year"
    /// Sources:
    /// 1. HR_Policy.pdf, page 4, "Vacation Policy" section
    /// 2. HR_Policy.pdf, page 5, "Paid Time Off" section
    /// 
    /// WHY CRITICAL FOR RAG?
    /// - Proves AI answer came from company documents
    /// - User can verify answer in original source
    /// - Prevents hallucinations (AI making up answers)
    /// - Compliance: Audit trail of information sources
    /// - Trust: Users believe answers are real, not AI invention
    /// </summary>
    public ICollection<MessageSource> Sources { get; set; } = new List<MessageSource>();

    /// <summary>
    /// Business rule: Check if this conversation has citations.
    /// 
    /// VALIDATION:
    /// - Answer should have at least one source
    /// - If no sources, might indicate AI hallucination
    /// - Could be error in retrieval system
    /// 
    /// EXAMPLE USAGE IN APPLICATION LAYER:
    /// if (!conversation.HasSources())
    /// {
    ///     _logger.Warning("Answer with no sources generated");
    ///     // Optional: Don't show answer without sources
    ///     throw new InvalidBusinessRuleException("Answer must have sources");
    /// }
    /// </summary>
    public bool HasSources() => Sources.Count > 0;

    /// <summary>
    /// Get a summary of sources for display.
    /// 
    /// EXAMPLE OUTPUT:
    /// "Sources: HR_Policy.pdf (pages 3-5), Employee_Handbook.pdf (page 12)"
    /// 
    /// WHY HELPER METHOD?
    /// - Encapsulates display logic
    /// - Can change format once instead of everywhere
    /// - Reusable in API responses
    /// </summary>
    public string GetSourcesSummary()
    {
        if (!HasSources())
            return "No sources";

        var documentGroups = Sources
            .GroupBy(s => new { s.DocumentName })
            .Select(g => $"{g.Key.DocumentName} (pages {string.Join(", ", g.Select(s => s.PageNumber).Distinct())})")
            .ToList();

        return $"Sources: {string.Join(", ", documentGroups)}";
    }
}
