namespace AIKnowledgeAssistant.Domain.Entities;

using AIKnowledgeAssistant.Domain.Enums;

/// <summary>
/// Represents an uploaded company document (PDF, Word, etc.).
/// 
/// DOMAIN RESPONSIBILITY:
/// - Track documents uploaded by users
/// - Store document metadata (name, type, upload time)
/// - Link documents to their owner (User)
/// 
/// WHY THIS STRUCTURE?
/// - Id: Unique identifier for this document
/// - FileName: Original filename (e.g., "HR_Policy_2024.pdf")
/// - FilePath: Where on disk/storage this file is saved
/// - FileType: PDF, DOCX, TXT, etc. (used for extraction logic)
/// - UploadedAt: When was this document added to system?
/// - UserId: Which user owns this document? (referential integrity)
/// 
/// BUSINESS RULES:
/// - Each document must belong to exactly one user
/// - Document cannot be shared between users (each user has their own copy)
/// - FileType must be one of the supported types
/// - FilePath should be immutable (don't move files after upload)
/// 
/// ARCHITECTURAL NOTE:
/// This entity demonstrates relationships:
/// - One User → Many Documents (one-to-many)
/// - One Document → Many DocumentChunks (one-to-many)
/// 
/// In Clean Architecture:
/// - Domain defines the relationship
/// - Infrastructure implements it in DbContext
/// - Application uses it through repositories
/// </summary>
public class Document
{
    /// <summary>
    /// Unique identifier for this document.
    /// GUID ensures uniqueness across distributed systems.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Original filename as uploaded by user.
    /// IMPORTANT: This is for display, not file operations!
    /// 
    /// EXAMPLE: "Employee_Handbook_2024.pdf"
    /// 
    /// WHY IMPORTANT?
    /// - Users want to see the original filename
    /// - Helps identify which document answered the question
    /// - Displayed in UI and in AI citations
    /// 
    /// SECURITY NOTE: Never use this for file operations
    /// Use FilePath instead (which is controlled by system)
    /// </summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Full path where the file is stored.
    /// 
    /// EXAMPLE:
    /// - Local: "/storage/documents/2024/07/guid-filename.pdf"
    /// - Cloud: "s3://bucket-name/documents/guid-filename.pdf"
    /// - Azure: "https://blob.azure.com/documents/guid-filename.pdf"
    /// 
    /// WHY ABSTRACTED?
    /// - Can switch storage providers without changing entity
    /// - Infrastructure layer controls where files are stored
    /// - Domain doesn't care if it's disk, S3, or Azure Blob
    /// 
    /// SECURITY NOTE: This path should be:
    /// - Generated by system (never user-provided)
    /// - Include GUID to prevent filename collisions
    /// - Prevent directory traversal attacks
    /// </summary>
    public string FilePath { get; set; } = string.Empty;

    /// <summary>
    /// Type of file (Pdf, Docx, Doc, Txt).
    /// Determines which extraction logic to use.
    /// 
    /// WHY USE ENUM?
    /// - Only valid file types allowed
    /// - Type-safe (compile-time checking)
    /// - Prevents invalid extraction attempts
    /// 
    /// PROCESSING LOGIC (in Infrastructure layer):
    /// if (FileType == FileType.Pdf)
    ///     text = await _pdfExtractor.ExtractAsync(FilePath);
    /// else if (FileType == FileType.Docx)
    ///     text = await _wordExtractor.ExtractAsync(FilePath);
    /// </summary>
    public FileType FileType { get; set; }

    /// <summary>
    /// When this document was uploaded to the system.
    /// 
    /// AUDIT TRAIL:
    /// - Know how old documents are
    /// - Compliance requirements (data retention)
    /// - Identify most recently updated content
    /// 
    /// NOTE: Using UTC to avoid timezone issues
    /// Set to DateTime.UtcNow when document is created
    /// </summary>
    public DateTime UploadedAt { get; set; }

    /// <summary>
    /// The user who owns/uploaded this document.
    /// Foreign key to User table.
    /// 
    /// BUSINESS RULE:
    /// - Every document must belong to exactly one user
    /// - If user is deleted, what happens to their documents?
    ///   (Cascade delete, or preserve for audit trail? - decided in Infrastructure)
    /// - Users can only access their own documents
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Navigation property to the User who owns this document.
    /// 
    /// WHY NAVIGATION PROPERTY?
    /// - Entity Framework uses this to load related User
    /// - Can eagerly load: context.Documents.Include(d => d.User)
    /// - In application: document.User.Email
    /// 
    /// Set by Entity Framework, not directly assigned
    /// </summary>
    public User? User { get; set; }

    /// <summary>
    /// Collection of chunks this document has been split into.
    /// 
    /// PROCESSING PIPELINE:
    /// 1. Upload: Create Document entity
    /// 2. Extract: Read file, get raw text
    /// 3. Chunk: Split text into chunks (e.g., 512 tokens each)
    /// 4. Embed: Generate vector for each chunk
    /// 5. Store: Create DocumentChunk entities with embeddings
    /// 6. Search: Find relevant chunks during RAG
    /// 
    /// WHY CHUNKS?
    /// - LLMs have token limits (e.g., GPT has 4K/8K/128K limit)
    /// - Can't send entire 100-page document to AI
    /// - Instead: find similar chunks, send top 3-5 chunks as context
    /// - More relevant answers because of targeted context
    /// </summary>
    public ICollection<DocumentChunk> Chunks { get; set; } = new List<DocumentChunk>();

    /// <summary>
    /// File size in bytes.
    /// 
    /// WHY TRACK THIS?
    /// - Validate upload limits (e.g., max 50MB)
    /// - Display in UI ("This document is 2.3 MB")
    /// - Storage quota management
    /// - Billing (if SaaS model)
    /// 
    /// NOTE: Could be derived from FilePath in Infrastructure layer,
    /// but storing here avoids repeated disk I/O
    /// </summary>
    public long FileSizeBytes { get; set; }

    /// <summary>
    /// Business rule: Check if file is large enough to be meaningful.
    /// 
    /// RATIONALE:
    /// - Empty files should be rejected
    /// - Very small files might be noise
    /// - Minimum 1KB ensures some actual content
    /// 
    /// EXAMPLE USAGE IN APPLICATION LAYER:
    /// if (!document.HasContent())
    ///     throw new InvalidBusinessRuleException("Document is too small");
    /// </summary>
    public bool HasContent() => FileSizeBytes > 1024; // Minimum 1KB

    /// <summary>
    /// Business rule: Check if file size is within acceptable limits.
    /// 
    /// WHY VALIDATE SIZE?
    /// - Large files can crash extractors
    /// - Storage limits prevent abuse
    /// - Processing time is proportional to size
    /// 
    /// Maximum 50MB = reasonable balance between
    /// - Small enough to process quickly
    /// - Large enough for real documents
    /// 
    /// EXAMPLE USAGE:
    /// if (!document.IsValidSize())
    ///     throw new InvalidBusinessRuleException("File exceeds 50MB limit");
    /// </summary>
    public bool IsValidSize() => FileSizeBytes <= 50_000_000; // 50MB
}
