namespace AIKnowledgeAssistant.Application.Interfaces;

/// <summary>
/// Contract for storing and deleting the raw bytes of uploaded files.
///
/// WHY THIS INTERFACE EXISTS (Dependency Inversion Principle):
/// The Application layer needs to "save a file" and "delete a file",
/// but it must NOT care HOW or WHERE that happens.
///   - Development: save to a local folder on disk
///   - Production:  save to Azure Blob Storage or AWS S3
/// By depending on this abstraction instead of concrete file APIs,
/// we can swap the storage provider with a single line of DI config,
/// without changing any business logic.
///
/// IMPORTANT DESIGN CHOICE:
/// This interface uses <see cref="Stream"/>, NOT ASP.NET Core's IFormFile.
/// IFormFile is a *web* type. Keeping it out of this interface means the
/// Application and Infrastructure layers stay free of any web dependency
/// and remain easy to unit test. The controller (the only web-aware code)
/// converts IFormFile into a Stream before calling us.
/// </summary>
public interface IFileStorageService
{
    /// <summary>
    /// Persist the given content and return the storage path/key that
    /// should be saved on the Document entity (Document.FilePath).
    /// </summary>
    /// <param name="content">The raw file bytes as a readable stream.</param>
    /// <param name="originalFileName">
    /// The user's original filename, used only to preserve the file extension.
    /// The stored filename itself is generated by the implementation (a GUID),
    /// never the user's name — this prevents collisions and path-traversal attacks.
    /// </param>
    /// <param name="cancellationToken">Allows the request to be cancelled.</param>
    /// <returns>The path/key where the file was stored.</returns>
    Task<string> SaveAsync(
        Stream content,
        string originalFileName,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Delete a previously stored file. Must be idempotent:
    /// deleting a file that no longer exists is a no-op, not an error.
    /// </summary>
    /// <param name="storedPath">The path/key returned earlier by SaveAsync.</param>
    /// <param name="cancellationToken">Allows the request to be cancelled.</param>
    Task DeleteAsync(
        string storedPath,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Open a previously stored file for reading (e.g. to extract its text).
    /// The caller owns the returned stream and must dispose it.
    /// </summary>
    /// <param name="storedPath">The path/key returned earlier by SaveAsync.</param>
    /// <param name="cancellationToken">Allows the request to be cancelled.</param>
    Task<Stream> OpenReadAsync(
        string storedPath,
        CancellationToken cancellationToken = default);
}
