// <auto-generated />
using System;
using AIKnowledgeAssistant.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIKnowledgeAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260711150432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("AI-generated answer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("When this Q&A occurred");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Question asked by user");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When answer was last updated (if corrected)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Conversations_UserId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Original filename as uploaded by user");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Full path where file is stored (S3, disk, etc)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasComment("File size in bytes");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasComment("File type: 0=Pdf, 1=Docx, 2=Doc, 3=Txt");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("When document was uploaded");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("Document owner (Foreign key to Users)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Documents_UserId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasComment("Sequential index of chunk within document");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Text content of this chunk");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("When chunk was created");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasComment("Original page number in document");

                    b.PrimitiveCollection<string>("VectorEmbedding")
                        .HasColumnType("jsonb")
                        .HasComment("Vector embedding for semantic similarity search (JSON array format)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_DocumentChunks_DocumentId");

                    b.HasIndex("VectorEmbedding")
                        .HasDatabaseName("IX_DocumentChunks_VectorEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("VectorEmbedding"), "gin");

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.MessageSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("When this source was cited");

                    b.Property<Guid>("DocumentChunkId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Document name (denormalized for performance)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasComment("Page number in source document");

                    b.Property<float>("RelevanceScore")
                        .HasColumnType("real")
                        .HasComment("Similarity score: 0.0 to 1.0");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_MessageSources_ConversationId");

                    b.HasIndex("DocumentChunkId")
                        .HasDatabaseName("IX_MessageSources_DocumentChunkId");

                    b.ToTable("MessageSources", (string)null);
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("When token was issued");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Device that created this token");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When this token expires");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Why was token revoked?");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When token was revoked (if applicable)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Hashed refresh token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("IX_RefreshTokens_ExpirationDate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("Token", "RevokedAt")
                        .HasDatabaseName("IX_RefreshTokens_Token_RevokedAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("When user account was created (UTC)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("User's email address - used for login");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User's first name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User's last name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Bcrypt hashed password - never plaintext");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("User's authorization level: 0=User, 1=Admin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("AIKnowledgeAssistant.Domain.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Conversations_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.Document", b =>
                {
                    b.HasOne("AIKnowledgeAssistant.Domain.Entities.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Documents_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("AIKnowledgeAssistant.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentChunks_Documents");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.MessageSource", b =>
                {
                    b.HasOne("AIKnowledgeAssistant.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Sources")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MessageSources_Conversations");

                    b.HasOne("AIKnowledgeAssistant.Domain.Entities.DocumentChunk", "DocumentChunk")
                        .WithMany()
                        .HasForeignKey("DocumentChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("DocumentChunk");
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AIKnowledgeAssistant.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("AIKnowledgeAssistant.Domain.Entities.User", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Documents");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
